---
name: Sanity Checks

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Validate Template
        uses: docker://hashicorp/packer:1.5.5
        run: |
          packer validate -syntax-only template.json
